spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: mcmanager
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  security:
    basic:
      enabled: false




